import Image from "next/image"
import loginImg from "../../../public/loginImg.svg"
import styles from "./styles.module.scss"
import Head from "next/head"

export default function Layout({ children }) {
    return (
        <>
            <Head>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/public/favicon.ico" />
                <title>Ishedule | Faça seu login</title>
            </Head>
            <div className={styles.containerCenter}>
                <aside>
                    <Image className={styles.loginImg} src={loginImg} alt="Login image" />
                </aside>
                <div className={styles.containerContent}>

                    {children}
                </div>
            </div>
        </>
    )
}