import Head from 'next/head'
import Image from 'next/image'
import { Button } from '@/components/Ui/button'
import styles from '@/styles/Home.module.scss'
import { Input } from '@/components/Ui/input'
import { useState } from 'react'
import Link from 'next/link'
import LoginImg from '../../public/loginImg.svg'
import googleIconImg from '../../public/googleIconImg.svg'
import facebookIconImg from '../../public/facebookIconImg.svg'

export default function Home() {
  const [name, setName] = useState('')
  const [password, setPassword] = useState('')
  const [loading, setLoading] = useState(false)
  const [showPassword, setShowPassword] = useState(false)

  return (
    <>
      <Head>
        <title>Ishedule - Faça seu login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.containerCenter}>
        <aside>
          <Image src={LoginImg} alt='login svg' className={styles.loginImg}/>
        </aside>
        <div className={styles.containerContent}>
          <h2>Entrar</h2>
          <form>
            <label>Email ou Telefone</label>
            <Input
            withEye={false}
              type='text'
              value={name}
              onChange={(e) => setName(e.target.value)}
            />
            <label>Senha</label>
            <Input
              withEye={true}
              onShow={() => setShowPassword(!showPassword)}
              type={showPassword ? 'text' : 'password'}
              value={password}
              onChange={(e) => setPassword(e.target.value)}
            />
            <Button
              type='submit'
              loading= {loading}
            >
              Entrar
            </Button>
          </form>

          <div className={styles.lineGroup}>
            <div className={styles.line}></div>
            <p>
              ou entrar com
              </p>
              <div className={styles.line}></div>
            </div>

            <div className={styles.buttonsLogin}>
              <button className={styles.btnGoogle}>
                <Image src={googleIconImg} alt="imagem do google"/>
              </button>
              <button className={styles.btnFacebook}>
                <Image src={facebookIconImg} alt="imagem do facebook"/>
              </button>
            </div>

            <Link href="/signup">
              <p className={styles.text}>Não possui uma conta? <strong>Cadastre-se</strong></p>
            </Link>

        </div>
      </div>

    </>
  )
}
